# Generated by Django 5.0.6 on 2024-07-03 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='user_text',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
